name: emissioneval
channels:
- main
- conda-forge
dependencies:
- arrow=0.13.1
- ipython=7.9.0
- jupyter=1.0.0
- matplotlib=3.1.3
- pandas=1.0.3
- pip=20.0.2
- python=3.8.2
- requests=2.23.0
- scipy=1.4.1
- shapely=1.6.4
- geopandas=0.6.1
- attrdict=2.0.1
- scikit-learn=0.23.2
- pip:
    - osmapi==1.2.*
    - polyline==1.3.*
    - anytree==2.6.*
    - utm==0.5.*
    - branca==0.3.*
    - folium==0.8.*
    - geojson==2.3.*
    - attrdict==2.0.1
    - pymongo==3.11.0
